/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
/* %include "lecture2_SR_preamble.sas" /nosource; */
/* Remove all output files. */
/* %hostdel; */

/* Start program with a null title. */
title;

/* DATA dataset; */
/*    INFILE 'file path and filename'; */
/*    INPUT variables; */
/* RUN; */
/*  */
/* FILENAME datain `file path and filename'; */
/* DATA dataset; */
/*    INFILE datain; */
/*    INPUT variables; */
/* RUN; */
/*  */
/* FILENAME datain `file path and filename'; */
/* DATA dataset; */
/*    INFILE datain; */
/*    INPUT variables; */
/* RUN; */

/*Example 2.1*/
FILENAME roster "/folders/myfolders/age.dat";
DATA age;
INFILE roster delimiter=",";
INPUT name $ age;
RUN;
PROC PRINT data=age;
RUN;


/*Example 2.2*/
FILENAME bankacct "/folders/myfolders/bankaccts.dat";
DATA bankacct;
INFILE bankacct firstobs=4 obs=6;
INPUT bank $12. balance type $;
RUN;
PROC PRINT DATA=bankacct;
RUN;

/*Example 2.3*/
DATA cash;
INPUT bank $ acctnum money;
PUT bank acctnum money;
DATALINES;
CHASE 1536253 50.32
PNCBANK 189273462 1563.82
FLEET 287363 20000.00
;
RUN;

/*Example 2.4*/
FILENAME dataout "/folders/myfolders/newcash.txt";
DATA cash;
INPUT bank $ acctnum money;
FILE dataout;
PUT @2 bank @13 acctnum @23 money;
DATALINES;
CHASE 1536253 50.32
PNCBANK 189273462 1563.82
FLEET 287363 20000
;
RUN;


/* Example 2.5 */
DATA agecopy;
SET age;
RUN;
PROC PRINT DATA=agecopy;
RUN;

/* DATA new-dataset; */
/*    SET old-dataset; /* copy from old-dataset */
/*    ...; /*statements that defines new variables, */
/* subset, delete variables, etc.) */
/* RUN; */

/* Example 2.6 */
DATA students;
INPUT id male schtype $ read write;
DATALINES;
147 1 pub 87 72    /*suppose 1 for male.*/
108 0 pub 74 63
18 0 pri 50 93
;
RUN;
DATA students1;
SET students;
total=read+write; /* add up read and write */
RUN;
PROC PRINT data=students1;
RUN;

/* Example 2.7 */
DATA students2;
INPUT id male schtype $ read write;
total = read + write;
DATALINES;
147 1 pub 87 72 /*suppose 1 for male.*/
108 0 pub 74 63
18 0 pri 50 93
;
RUN;
PROC PRINT data=students2;
RUN;

/* Example 2.8 */
DATA students3;
set students;
if read>=90 then readgrade="A";
if 80<=read<90 then readgrade="B";
if 70<=read<80 then readgrade="C";
if 60<=read<70 then readgrade="D";
if read<60 then readgrade="F"
;
RUN;
PROC PRINT data=students3;
RUN;

/* Example 2.9 */
DATA students4;
set students;
total=read+write;
if total>=120 then totalgrade='PASS';
else totalgrade='FAIL';
RUN;
PROC PRINT data=students4;
RUN;

/* Example 2.10 */
DATA studentsdrop;
set students;
drop read;
RUN;
PROC PRINT data=studentsdrop;
RUN;

DATA studentskeep;
set students;
keep id male schtype write;
RUN;
PROC PRINT data=studentskeep;
RUN;

/*Example 2.11 */
/* DATA studentsrename; */
/* SET studentsl; */
/* RENAME read=read-score; */
/* RUN; */
/* PROC PRINT data=studentsrename; */
/* RUN; */

/* Example 2.12 */
DATA Boys;
SET students;
IF male=1;  /* Equivalent to IF male=0 then DELETE; */
RUN;
PROC PRINT data=Boys;
RUN;

/* Example 2.13*/
DATA Boys Girls; /*Create two datasets */
SET students;
IF male=1 THEN OUTPUT Boys;
ELSE OUTPUT Girls;
RUN;
PROC PRINT DATA=Boys;
RUN;
PROC PRINT DATA=Girls;
RUN;

/* PROC SORT DATA=dataset-1 OUT=dataset-2 NODUPKEY; */
/* BY variable-1 descending variable-2 ... ; */

/* Example 2.14 */
DATA marine;
INPUT Name $ Family $ Length @@;
Datalines;
Beluga whale 15 Whale shark 40 Basking shark 30
Gray whale 50 Mako shark 12 Sperm whale 60
Dwarf shark .5 Whale shark 40 Humpback . 50
Blue whale 100 Killer whale 30
;
Run;
PROC SORT DATA=marine OUT=seasort NODUPKEY;
BY Family DESCENDING Length;
Run;
PROC PRINT DATA=seasort;
Run;

DATA YR1998;
INPUT Day $ 1-5 Temp Weather $ 10-15;
DATALINES;
Jan 1 33 sun
Jan 2 35 sun
Jan 3 45 clouds
Jan 5 28 snow
;
RUN;

DATA YR1999;
INPUT Day $ 1-5 Temp;
DATALINES;
Jan 1 25
Jan 2 20
Jan 3 35
Jan 6 40
Jan 8 39
; 
RUN;

/* Example 2.15 */
DATA combined1;
SET YR1998 YR1999;
RUN;
PROC PRINT data=combined1;
RUN;

/* Example 2.16 */
PROC SORT data=YR1998;
BY Day; RUN;
PROC SORT data=YR1999;
BY Day; RUN;
DATA combined2;
SET YR1998 YR1999;
BY Day; RUN;
PROC PRINT data=combined2; RUN;

/* Example 2.16 */
DATA combined3;
MERGE YR1998 YR1999;
RUN;
PROC PRINT data=combined3;
RUN;

/* Example 2.17 */
DATA combined4;
MERGE YR1998 YR1999;
BY Day;
RUN;
PROC PRINT data=combined4;
RUN;